DROP DATABASE IF EXISTS Company;
CREATE DATABASE Company;
USE Company;

CREATE TABLE Employee (
	SSN CHAR(9) UNIQUE NOT NULL,
	Name VARCHAR(32) NOT NULL,
	CONSTRAINT Employee_PK PRIMARY KEY (SSN)
);

CREATE TABLE Project (
	ID INT NOT NULL AUTO_INCREMENT,
	Name VARCHAR(32) NOT NULL,
	CONSTRAINT Project_PK PRIMARY KEY (ID)
);

CREATE TABLE Works_on (
	SSN CHAR(9) NOT NULL,
	ProjectID INT NOT NULL,
	CONSTRAINT Works_on_PK PRIMARY KEY (SSN, ProjectID),
	CONSTRAINT Works_on_FK1 FOREIGN KEY (SSN) REFERENCES Employee(SSN),
	CONSTRAINT Works_on_FK2 FOREIGN KEY (ProjectID) REFERENCES Project(ID)
);

